pipeline {
    agent none

    stages {
      
        stage('build') {
          agent {
              docker {
                  image 'python:2-alpine'
              }
          }
                    
            when{
                changeset "**/vote/**"
            }
            steps {
                echo 'Compiling vote app'
                dir('vote'){
                    sh 'python -m py_compile sources/add2vals.py sources/calc.py'
                    sh 'pip install --upgrade pip'
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        
        stage('test') {
          agent {
              docker {
                  image 'qnib/pytest'
              }
          }
            when{
                changeset "**/vote/**"
                
            }
            steps {
                echo 'Running Unit Tests on vote app'
                dir('vote'){
                    sh 'nosetests -v'
                }
                
            }
        }
      }
        
    post{
      always{
        
        echo 'Job completed.'
      }
    }
}
